name: producer

services:
  api:
    image: ghcr.io/maximbacar/producer-api:latest
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "8000:8000"
    env_file:
      - .env.local

  frontend:
    image: ghcr.io/maximbacar/producer-webapp:latest
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "3000:3000"
    depends_on:
      - api

networks:
  internal:
    driver: bridge